FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Eventos API

Backend do projeto de eventos.

## Evento [/evento]

### Listar todos os Eventos [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "nome": "Mobilização: Avanços da Pauta Municipalista",
                "data": "11:09 PM - 1 Jan 2016",
                "descricao": "Convocamos todos os municipalistas a estarem em Brasília."
            }
        ]

### Novo Evento [POST]

+ Request (application/json)

        {
            "nome": "Mobilização: Avanços da Pauta Municipalista",
            "data": "11:09 PM - 1 Jan 2016",
            "descricao": "Convocamos todos os municipalistas a estarem em Brasília."
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "id": 1,
                "nome": "Mobilização: Avanços da Pauta Municipalista",
                "data": "11:09 PM - 1 Jan 2016",
                "descricao": "Convocamos todos os municipalistas a estarem em Brasília."
            }

### Atualizar Evento [PUT]

+ Request (application/json)

        {
            "id": 1,
            "nome": "Mobilização: Avanços da Pauta Municipalista",
            "data": "11:09 PM - 1 Jan 2016",
            "descricao": "Convocamos todos os municipalistas a estarem em Brasília."
        }

+ Response 200 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "id": 1,
                "nome": "Mobilização: Avanços da Pauta Municipalista",
                "data": "11:09 PM - 1 Jan 2016",
                "descricao": "Convocamos todos os municipalistas a estarem em Brasília."
            }
            
### Excluir Evento [DELETE]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "id": 1,
                "message": "Excluido com sucesso!"
            }